query MainFeed {
    feed {
        __typename
        id
        name
        published
        creator {
            id,
            name
        }
        favorited_by {
            id,
            name,
        }
        ingredients {
            id,
            name,
            alcoholic
        }
    }
}